### ISSUE TITLE
Error: undefined symbol: createAgoraService

### ISSUE THREAD

**Issue by zhangcunxiang** [AgoraIO-Community/Agora-RTM-Nodejs#11]
After I finished every config and move files I want to run test unit. And when I enter command:
> npm run test

Got the error: 
```
 FAIL  ./adpter.test.ts
  ● Test suite failed to run

    Cannot find module '../src' from 'adpter.test.ts'

    > 1 | import AgoraRTM from '../src'
        | ^
      2 | 
      3 | describe('Adapter API Test', () => {
      4 |   it('Join/Leave', async () => {

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:202:17)
      at Object.<anonymous> (adpter.test.ts:1:1)


 RUNS  __tests__/rtm.test.ts
node: symbol lookup error: /home/ubuntu/Agora-RTM-Nodejs/build/Release/agorasdk.node: undefined symbol: createAgoraService
```

**Comment by zhangcunxiang** [comment]
@plutoless Can you help me confirm or I need to contact my BD ?

**Comment by plutoless** [comment]
did you upgrade your rtm sdk?

**Comment by zhangcunxiang** [comment]
Thanks for your reply @plutoless. I'm not sure but I got the sdk from this link:
> https://download.agora.io/rtmsdk/release/Agora_RTM_SDK_for_Linux_v1_2_2.zip?_ga=2.32470457.609247164.1579402511-1643312338.1569476224

Seems like it's a new version SDK.

**Comment by plutoless** [comment]
looks like they have changed apis in latest version. if you can find old version SDK maybe it will still be working. otherwise i will need to re-adapt the latest one

**Comment by zhangcunxiang** [comment]
@plutoless You mean v1.2.1 ?

**Comment by zhangcunxiang** [comment]
@plutoless I think no matter I can find the old version you should make your project could be run and you'd better keep that lib files in this project not let us find & download form other places.

**Comment by plutoless** [comment]
ok i'll do the adapt tonight. i didn't realize they would make headers incompatible at first place.

**Comment by plutoless** [comment]
ill update the dependent lib onto release so that you can find it later.

**Comment by plutoless** [comment]
@zhangcunxiang i have provided a new npm script
```
npm run sync:lib
```
to automatically download the dependent lib so it won't get lost for future updates. i've also adapted to latest RTM SDK version. The tests are all passing now.
