### ISSUE TITLE
Using Agora-RTM-Nodejs from another project

### ISSUE THREAD

**Issue by homerlex** [AgoraIO-Community/Agora-RTM-Nodejs#3]
I now have Agora-RTM-Nodejs installed and the tests passing.  I want to create a nodejs project that now uses Agora-RTM-Nodejs (not using typescript).  Could you provide an example on how to use Agora-RTM-Nodejs from another nodejs project?

I've tried doing something like the following but its not working out:
```
const AgoraRTM = require('../Agora-RTM-Nodejs');
const engine = AgoraRTM.createInstance();
engine.initialize(process.env.AGORA_APP_ID);
engine.login(null, 'ttyy');
```

Am I on the right track?  A JS example using this library would go a long way.

**Comment by homerlex** [comment]
FYI - I believe the above code is actually working.  I added a listener on the LoginSuccess event an it is being called.  What wasn't working was trying to join a channel too quickly after calling login.  I changed my code so that channel.join is being called in LoginSuccess:

```
    engine.onEvent('LoginSuccess', () => {
        console.log('Login Success!!!');
        channel.join();        
    });
```

**Comment by plutoless** [comment]
yes you need to ensure you have successfully logged in before you start joining a channel
