### ISSUE TITLE
What files should I use after I generate release files with command 'npm run build:ts'

### ISSUE THREAD

**Issue by zhangcunxiang** [AgoraIO-Community/Agora-RTM-Nodejs#4]
I want to use the generated files for an exist nodejs project. Can you tell me how to use ? Do you have any documentation to read ?

**Comment by plutoless** [comment]
the usage guide is in readme already. do you need to use it in linux environment?

**Comment by zhangcunxiang** [comment]
Thank you for quickly response. But I can only see `Run command above to generate build/ & dist/ which contains node addon and js api.` which is useful for me. I have got the generated build and dist folder but how to use the files generated in my nodejs project?

**Comment by plutoless** [comment]
Just require the js file in dist folder from your nodejs server project and you can start using it.
The docs can be found here
https://docs.agora.io/en/Real-time-Messaging/product_rtm?platform=All%20Platforms

**Comment by zhangcunxiang** [comment]
Thanks @plutoless for your help. But here are some questions for you:
1. Do you have plan to or will your team provide a more easily use node SDK no need user to compile and move files their self?
2. I checked the test codes and C++ file noticed that there are some missing method you provided with web sdk like `checkStatus` of user status. Could you add that?
Our product just want to use your RTM to check user status and decide to send user some real time messages. If your team will not support we have to switch to other products that provides more complete functions.

**Comment by plutoless** [comment]
1. currently there's no plan to provide prebuilt binaries as there are simply too many of node/os version we need to support. but we have provided a docker image for you to start with, which hopefully can help you start easier
2. we have plans to add these apis in upcoming months, we can also accelerate the process if you can talk to your BD/customer support team to raise your feature request.

**Comment by zhangcunxiang** [comment]
@plutoless Okay.

**Comment by zhangcunxiang** [comment]
So this ticket will close if you complete your nodejs RTM SDK by adding query_user_status api.

**Comment by plutoless** [comment]
@zhangcunxiang  just to double check, you are talking about this api right? https://docs.agora.io/cn/Real-time-Messaging/API%20Reference/RTM_cpp/classagora_1_1rtm_1_1_i_rtm_service.html#a3add0055c4455dc8d04bfc37edfd8e94

**Comment by zhangcunxiang** [comment]
@plutoless Correct.

**Comment by plutoless** [comment]
done
